name: 'fal_sagemaker_example'
version: '1.0.0'
config-version: 2

profile: 'fal'

model-paths: ["models"]
data-paths: ["data"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
