version: 2

sources:
  - name: results
    database: test
    schema: dbt_fal
    tables:
      - name: earning_predictions

models:
  - name: features
    config:
      materialized: table
    meta:
      fal:
        scripts:
          after:
            - train_deploy_sagemaker.py

  - name: labels
    config:
      materialized: table
