version: 2

models:
  - name: training_sample
    config:
      materialized: table

  - name: sagemaker_models
    meta:
      fal:
        scripts:
          after:
            - train.py

  - name: sample_batch
    config:
      materialized: table

  - name: sample_batch_with_predictions
    meta:
      fal:
        scripts:
          after:
            - predict.py
