version: 2

sources:
  - name: results
    database: test
    schema: dbt_fal
    tables:
      - name: sagemaker_models

models:
  - name: features
    config:
      materialized: table

  - name: labels
    config:
      materialized: table

  - name: sagemaker_models
    meta:
      fal:
        scripts:
          after:
            - train.py

  - name: sample_batch
    config:
      materialized: table
    meta:
      fal:
        scripts:
          after:
            - predict.py
